/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.forms;

import static project.Utils.capitalizeEnum;

import java.time.Duration;
import java.util.List;
import java.util.stream.Stream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import project.entities.CourseAttendable;
import project.entities.Lab;
import project.entities.Lecture;
import project.entities.Room;
import project.entities.Teacher;

/** @author moata */
public class CourseAttendableForm extends javax.swing.JDialog {
  private static final int MAX_DURATION = 6;

  private final List<Teacher> teachers;
  private final List<Room> rooms;

  private CourseAttendable attendable;

  /** Creates new form CourseAttendableForm */
  public CourseAttendableForm(JDialog owner, List<Teacher> teachers, List<Room> rooms) {
    super(owner, true);

    this.teachers = teachers;
    this.rooms = rooms;

    initComponents();
    setSize(365, 270);
    setLocationRelativeTo(owner);

    typeComboBox.setModel(
        new DefaultComboBoxModel<>(
            new String[] {
              capitalizeEnum(CourseAttendable.Type.LECTURE),
              capitalizeEnum(CourseAttendable.Type.LAB)
            }));

    var teacherStrings = teachers.stream().map(Teacher::getName).toArray(String[]::new);
    teacherComboBox.setModel(new DefaultComboBoxModel<>(teacherStrings));

    var roomStrings = rooms.stream().map(Room::getName).toArray(String[]::new);
    roomComboBox.setModel(new DefaultComboBoxModel<>(roomStrings));

    var durations = new String[MAX_DURATION];
    for (int i = 0; i < durations.length; i++) {
      durations[i] = "" + (i + 1);
    }
    durationComboBox.setModel(new DefaultComboBoxModel<>(durations));
  }

/*  private String[] filterRooms(CourseAttendable.Type type) {
    return rooms.stream()
        .filter(
            r ->
                r.getType()
                    == (type == CourseAttendable.Type.LECTURE
                        ? Room.Type.CLASSROOM
                        : Room.Type.LABORATORY))
        .map(Room::getName)
        .toArray(String[]::new);
  }*/

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    teacherComboBox = new javax.swing.JComboBox<>();
    roomComboBox = new javax.swing.JComboBox<>();
    durationComboBox = new javax.swing.JComboBox<>();
    typeComboBox = new javax.swing.JComboBox<>();
    saveButton = new javax.swing.JButton();
    discardButton = new javax.swing.JButton();

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel1.setText("Type:");

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel2.setText("Teacher:");

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel3.setText("Room:");

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel4.setText("Duration:");

    teacherComboBox.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));

    roomComboBox.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));

    durationComboBox.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));

    typeComboBox.setModel(
        new javax.swing.DefaultComboBoxModel<>(
            new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));

    saveButton.setText("Save Changes");
    saveButton.setActionCommand("addButton");
    saveButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveButtonActionPerformed(evt);
          }
        });

    discardButton.setText("Discard Changes");
    discardButton.setActionCommand("discardButton");
    discardButton.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            discardButtonActionPerformed(evt);
          }
        });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jLabel1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        59,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        typeComboBox,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        266,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jLabel2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        59,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        teacherComboBox,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        266,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jLabel3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        59,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        roomComboBox,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        266,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jLabel4,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        59,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(
                                        durationComboBox,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        266,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        saveButton,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        154,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                        discardButton,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)))
                    .addContainerGap(16, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jLabel1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                24,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                typeComboBox,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                24,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jLabel2,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                24,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                teacherComboBox,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                24,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jLabel3,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                24,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                roomComboBox,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                24,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jLabel4,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                24,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                durationComboBox,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                24,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                saveButton,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                30,
                                Short.MAX_VALUE)
                            .addComponent(
                                discardButton,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                30,
                                Short.MAX_VALUE))
                    .addContainerGap()));
  } // </editor-fold>//GEN-END:initComponents

//  private void typeComboBoxActionPerformed(
//      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_typeComboBoxActionPerformed
//    @SuppressWarnings("unchecked")
//    var source = (JComboBox<String>) evt.getSource();
//    switch (source.getSelectedIndex()) {
//      case 0: // Lecture
//        roomComboBox.setModel(
//            new DefaultComboBoxModel<>(filterRooms(CourseAttendable.Type.LECTURE)));
//        break;
//
//      case 1: // Lab
//        roomComboBox.setModel(
//            new DefaultComboBoxModel<>(filterRooms(CourseAttendable.Type.LAB)));
//        break;
//
//      default: // do nothing
//    }
//  } // GEN-LAST:event_typeComboBoxActionPerformed

  private void saveButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_saveButtonActionPerformed
    if (!allSelected()) {
      JOptionPane.showMessageDialog(this,
          "All items must be selected",
          "Invalid selection",
          JOptionPane.ERROR_MESSAGE);
      return;
    }

    if (typeComboBox.getSelectedIndex()
        != rooms.get(roomComboBox.getSelectedIndex()).getType().ordinal()) {
      JOptionPane.showMessageDialog(this,
          "Type must match selected room type",
          "Invalid selection",
          JOptionPane.ERROR_MESSAGE);
      return;
    }

    switch (typeComboBox.getSelectedIndex()) {
      case 0: // Lecture
        attendable = new Lecture.Builder()
            .setRoom(rooms.get(roomComboBox.getSelectedIndex()))
            .setTeacher(teachers.get(teacherComboBox.getSelectedIndex()))
            .setDuration(Duration.ofHours(durationComboBox.getSelectedIndex() + 1))
            .build();
        break;

      case 1: // Lab
        attendable = new Lab.Builder()
            .setRoom(rooms.get(roomComboBox.getSelectedIndex()))
            .setTeacher(teachers.get(teacherComboBox.getSelectedIndex()))
            .setDuration(Duration.ofHours(durationComboBox.getSelectedIndex() + 1))
            .build();
        break;

      default:
        throw new IllegalStateException("what?");
    }

    dispose();
  } // GEN-LAST:event_saveButtonActionPerformed

  private void discardButtonActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_discardButtonActionPerformed
    dispose();
  } // GEN-LAST:event_discardButtonActionPerformed

  private boolean allSelected() {
    return Stream.of(typeComboBox, teacherComboBox, roomComboBox, durationComboBox)
        .mapToInt(JComboBox::getSelectedIndex)
        .noneMatch(i -> i < 0);
  }

  public CourseAttendable getInsertedAttendable() {
    return attendable;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton discardButton;
  private javax.swing.JComboBox<String> durationComboBox;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JComboBox<String> roomComboBox;
  private javax.swing.JButton saveButton;
  private javax.swing.JComboBox<String> teacherComboBox;
  private javax.swing.JComboBox<String> typeComboBox;
  // End of variables declaration//GEN-END:variables
}
